### ISSUE TITLE
Running continunous integration tests with GPU

### ISSUE THREAD

**Issue by alexmorley** [rossant/pykilosort#23]
I started looking at running the tests that require GPU using hosted continuous integration tools (see https://github.com/alexmorley/pykilosort/issues/2#issuecomment-623104259) but few of them offer it and those that do are eye-wateringly expensive. I can't find it for less than $5k / month and even that won't be fully managed. 

I think its *really* valuable to have these tests automated and reproducible ...

... so I have set up a custom Jenkins instance on an existing machine I have with a GPU. It's at [jenkins.alexmorley.me](https://jenkins.alexmorley.me) and I can add anyone an account if they need it. I have it set up on my fork to run against pull requests and report the status (e.g. https://github.com/alexmorley/pykilosort/pull/12).

Works nicely and it's pretty much free (- a bit of electricity but I can take the hit on that one :smile:). At some point, I'll need @rossant to add a couple of bits of info into the Admin Settings of this repo so we can have it here too.

**Comment by rossant** [comment]
Excellent, thanks for looking into it. I agree that a custom dedicated machine is the way to go here.

> At some point, I'll need @rossant to add a couple of bits of info into the Admin Settings of this repo so we can have it here too.

Do you mean we can integrate your own server into this GitHub repository's status reporting system, using e.g. GitHub Actions?

**Comment by alexmorley** [comment]
> Do you mean we can integrate your own server into this GitHub repository's status reporting system, using e.g. GitHub Actions?

Yep but no need to use github actions. Just add a webhook that tell's the server when things have happened on the repo (to avoid polling).

**Comment by alexmorley** [comment]
done but needs to be migrated to bigger server

**Comment by alexmorley** [comment]
see #36
