### ISSUE TITLE
Replicating Matlab GUI for pykilosort

### ISSUE THREAD

**Issue by shashwatsridhar** [rossant/pykilosort#24]
Kilosort2 comes with a Graphical User Interface (GUI) using which the user can load, preprocess and spike sort the data. Such a GUI has not yet been implemented in PyKilosort. This issue roughly outlines the tasks required to replicate this feature.

- [x] Implement the basic structure of the GUI using PyQt5 (Settings, Probe view, Data view, Run panel, Message log)
- [x] Ensure all input fields in the Settings panel work completely (type checking for inputs, file dialogs for datafile/working folder/results folder, advanced options)
- [x] Sub-class one of pyqtgraph's widgets (Graphics Widget?) for the Data view and modify the mouse behaviour so that it mimics the functionality of the Matlab GUI
- [x] Load and view traces from sample datasets into the Data view
- [x] Connect the "seek" plot to the main data plot (using functions from preprocess.py to filter/whiten data on the fly)
- [x] Load and view sample probe layout, implement interactivity so that clicking on a channel in the Probe view shows corresponding traces in the Data view
- [x] Link the different steps of the spike sorting pipelines (preprocess, spikesort, export) to the corresponding buttons in the GUI
- [x] Redirect all stdout to the message log

**Comment by rossant** [comment]
:+1:
BTW very preliminary work on the GUI can be found here (based on phy and PyQt5) https://github.com/rossant/pykilosort/blob/master/pykilosort/gui.py

**Comment by alexmorley** [comment]
@shashwatsridhar you wanna update this with all your recent work? I reckon almost all of this is done.

**Comment by shashwatsridhar** [comment]
Thanks for the reminder, @alexmorley that's a good idea!

The GUI is almost ready, since you can already do the following:

- Load datasets and corresponding probe files
- Preprocess data, spike sort it and export the results to a Phy compatible format
- Scrub through the data using keyboard / mouse interactivity (scrubbing is reasonably fast)
- View the raw, whitened and predicted traces / colormaps of the loaded data
- View and edit all sorting parameters from within the GUI (accessible from the "Advanced Options..." dialog)
- View all console output in the GUI itself
- Create new probe files using numpy commands

The only major feature remaining is the ability to view the residual traces. I'm currently working on it, and I should have it ready pretty soon. That would probably be a good time to merge the pull request, I guess? After that is over, the focus would be on improving speed to make it comparable to the Kilosort GUI, and addressing the many minor bugs that exist.

**Comment by alexmorley** [comment]
> That would probably be a good time to merge the pull request, I guess?

Even before if you like. But yes let's merge it then at the latest :) @ me and I can give it a final review any time.

**Comment by shashwatsridhar** [comment]
@alexmorley a slightly buggy but feature-complete version of the GUI is ready for merging. The residual view works as well. Could you review it when you find some time? (a couple of suggestions from your previous review are still pending, I'm sorry :see_no_evil: the README update, for instance). I'll work on those early next week, but we can already merge before that if you want!

**Comment by alexmorley** [comment]
:ship: Merged.

https://github.com/rossant/pykilosort/pull/38 <-- check out this one where I've done some of the suggestions :)
