### ISSUE TITLE
Update pip version of phylib and add as dependency

### ISSUE THREAD

**Issue by m-beau** [rossant/pykilosort#8]
I had to install phylib straight from the master branch with

`pip install git+https://github.com/cortex-lab/phylib.git`

since a regular `pip install phylib` did not work (`ImportError: cannot import name 'get_ephys_reader' from 'phylib.io.traces'`)

So:
1) Update phylib version uploaded on pypi
2) Add phylib to dependencies.txt

**Comment by rossant** [comment]
Yes the doc should be updated to add the master dependency of phylib
And a release of phylib is planned for very soon I believe @oliche

**Comment by alexmorley** [comment]
Actually this should be fixed already (we point to latest phylib now). LMK if this is still an issue.
